name: zksync2_test
channels:
  - defaults
dependencies:
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - base58==2.1.1
    - bitarray==1.2.2
    - build==0.8.0
    - cached-property==1.5.2
    - charset-normalizer==2.0.12
    - cytoolz==0.11.2
    - docopt==0.6.2
    - eip712-structs==1.1.0
    - eth-abi==2.2.0
    - eth-account==0.5.7
    - eth-bloom==1.0.4
    - eth-hash==0.3.2
    - eth-keyfile==0.5.1
    - eth-keys==0.3.4
    - eth-rlp==0.2.1
    - eth-tester==0.6.0b6
    - eth-typing==2.3.0
    - eth-utils==1.10.0
    - frozenlist==1.3.0
    - hexbytes==0.2.2
    - idna==3.3
    - importlib-resources==5.7.1
    - ipfshttpclient==0.8.0a2
    - jsonschema==4.5.1
    - lru-dict==1.1.7
    - multiaddr==0.0.9
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - netaddr==0.8.0
    - packaging==21.3
    - parsimonious==0.8.1
    - pep517==0.13.0
    - pipreqs==0.4.11
    - protobuf==3.20.1
    - py-ecc==5.2.0
    - py-evm==0.5.0a3
    - py-geth==3.8.0
    - py-solc-x==1.1.1
    - pycryptodome==3.14.1
    - pyethash==0.1.27
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pysha3==1.0.2
    - requests==2.27.1
    - rlp==2.0.1
    - semantic-version==2.10.0
    - six==1.16.0
    - sortedcontainers==2.4.0
    - tomli==2.0.1
    - toolz==0.11.2
    - trie==2.0.0a5
    - typing-extensions==3.10.0.2
    - urllib3==1.26.9
    - varint==1.0.2
    - web3==5.30.0
    - websockets==9.1
    - yarg==0.1.9
    - yarl==1.7.2
    - zipp==3.8.0
